---
galaxy_info:
  author: Evgeniy Malanyuk
  description: Роль для разворачивания и конфигурирования файл сервера Samba
  company: Croc Inc.
  license: GPLv2
  min_ansible_version: '2.9'
  galaxy_tags: []
dependencies: []
