galaxy_info:
  author: Evgeniy Malanyuk
  description: Роль для разворачивания вторичного кнтроллера домена
  company: Croc Inc.
  license: GPLv2
  min_ansible_version: '2.9'
  galaxy_tags: []
dependencies: []
