---
## Запуск роли для создания пользователя и переименования серверов. Пользователь в дальнейшем будет использовать ansible. Имена серверов из файла inventory
# Запуск из под root:
# ansible-playbook base.yml --extra-vars='ansible_user=root ansible_ssh_pass="P@ssw0rd"' -K -k

# Запуск от имени root:
# ansible-playbook l1/adduser.yaml --extra-vars='ansible_user=root ansible_ssh_pass="P@ssw0rd"' -K -k
- name: Добавление пользвателя и переименование сервера из файла inventory
  become: true
  become_user: root
  hosts: all
  roles:
    - base_setup
