# ---
# - name: Предварительная подготовка серверов
#   become: true
#   hosts: all
#   # hosts: primary_dc
#   roles:
#     - role: preconfig
#       tags: preconfig

- name: Предварительная подготовка серверов
  become: true
  hosts: smb
  # hosts: primary_dc
  roles:
    - role: preconfig
      tags: preconfig

- name: Первичный DC
  become: true
  hosts: primary_dc
  roles:
    - role: dns
      tags: dns
    - role: dc
      tags:
        - install_dc
        - "[never, reinstall_dc]"

- name: Резервный DC
  become: true
  hosts: replica_dc
  roles:
    - role: dns
      tags: dns
    - role: dc
      tags:
        - install_dc
        - "[never, reinstall_dc]"
