---
- name: Предварительная подготовка серверов
  become: true
  hosts: all
  roles:
    - role: preconfig
      tags: preconfig

- name: Первичный DC
  become: true
  hosts: primary_dc
  roles:
    - role: bind
      tags: install_dc, bind
    - role: dc
      tags:
        - install_dc
        - "[never, reinstall_dc]"

- name: Резервный DC
  become: true
  hosts: replica_dc
  roles:
    - role: bind
      tags: install_dc, bind
    - role: dc
      tags:
        - install_dc
        - "[never, reinstall_dc]"

- name: Файл сервер
  become: true
  hosts: smb
  roles:
    - role: smb
      tags: install_smb

- name: DHCP сервер
  become: true
  hosts: dhcp
  roles:
    - role: join
    - role: dhcp
      tags: install_dhcp
