---
- name: Test
  hosts: aus177
  become: true

  tasks:
    - name: Replica_dc
      ansible.builtin.debug:
        msg: "{{ ansible_enp1s0 }}"
      # when: inventory_hostname in groups["replica_dc"]
