---
- name: Test
  hosts: aus128
  gather_facts: false
  become: true

  tasks:
    - name: Replica_dc
      ansible.builtin.debug:
        var: groups['dc']
      # loop: "{{ groups['dc'] }}"
      # when: inventory_hostname in groups["replica_dc"]
