---
- name: Установка скрипта для ввода в домен
  ansible.builtin.dnf:
    name: "join-to-domain"
    update_cache: true
    state: present

- name: Установка доменного DNS для сервера {{ inventory_hostname }}
  ansible.builtin.include_role:
    name: dns
  vars:
    dns_servers: "{{ dns_internal }}"

- name: Проверка, что сервер в домене или нет
  ansible.builtin.command: >
    adcli testjoin
  ignore_errors: true
  register: domain_joined
  changed_when: domain_joined.rc != 0

- name: Ввод сервера в домен
  when: domain_joined.failed
  ansible.builtin.command: >
    join-to-domain.sh
    -d {{ realm }}
    -n {{ inventory_hostname }}
    -u {{ domain_admin }}
    -p {{ administrator_domain_password | quote }} -y
  register: dc_result
  changed_when: dc_result.rc != 0

- name: Перезагрузка сервера после ввода в домен
  when: domain_joined.failed
  ansible.builtin.reboot:

- name: Блок конфигурации chrony при необходимости
  when: update_chrony_conf | default('false')
  block:
    - name: Добавдение pool ntp
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        regexp: "server"
        line: "pool astrakhan-dobycha.gazprom.ru iburst"
        state: present
    - name: Добавдение maxdistance 16.0
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        line: "maxdistance 16.0"
        state: present
    - name: Перезапуск chrony
      ansible.builtin.service:
        name: chronyd
        state: restarted
