all:
  children:
    dc:
      hosts:
        dc-100:
          ansible_host: 172.26.71.81
          ansible_port: 22151
        dc-101:
          ansible_host: 172.26.71.81
          ansible_port: 22152
    primary_dc:
      hosts:
        dc-100:
    replica_dc:
      hosts:
        dc-101:
    dhcp:
      hosts:
        aus172:
          ansible_host: 172.26.71.81
          ansible_port: 22200
        aus177:
          ansible_host: 172.26.71.81
          ansible_port: 22201
    smb:
      hosts:
        aus128:
          ansible_host: 172.26.71.81
          ansible_port: 22153
dns:
  children:
    dc:
