all:
  children:
    dc:
      hosts:
        h1.test:
          ansible_host: 172.26.71.81
          ansible_port: 2222
        h4.test:
          ansible_host: 172.26.71.81
          ansible_port: 2225
    dhcp:
      hosts:
        h2.test:
          ansible_host: 172.26.71.81
          ansible_port: 2223
        h3.test:
          ansible_host: 172.26.71.81
          ansible_port: 2224
primary_dc:
  hosts:
    h1.test:
replica_dc:
  hosts:
    h4.test:
dns:
  children:
    dc:
