---
# Создание пользователя для запуска ansible-playbook
# Пароль задается из переменной {{ ansible_become_pass }}
- name: "Создане пользователя и добавление в группу wheel"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    groups:
      - wheel
    append: true
    password: "{{ ansible_become_pass | password_hash('sha512', 'mysecretsalt') }}"
    update_password: always
