---
- name: Создание пользователя
  ansible.builtin.include_tasks: "adduser.yaml"
  when: base_setup_create_user

- name: Переименование сервера из inventory
  ansible.builtin.include_tasks: "servername.yml"
  when: base_setup_rename_server
