---
ansible_user: admin
ansible_ssh_pass: '!QAZxsw2'
ansible_become_pass: '!QAZxsw2'
base_packets:
  - bash-completion
services:
  - pkg: firewalld
    name: firewalld
  - pkg: qemu-guest-agent
    name: qemu-guest-agent

realm: adb.gazprom.ru
