---
ansible_user: admin
ansible_ssh_pass: '!QAZxsw2'
ansible_become_pass: '!QAZxsw2'

## Изменения адреса в репозитории для всех серверов
repo_url: "https://repo1.red-soft.ru/redos/7.3/"

## Адрес внешнего DNS
dns_external:
  - 192.168.100.1
  - 192.168.100.2

## Адрес внутреннего DNS (адреса контроллеров)
dns_internal:
  - 192.168.100.16
  - 192.168.100.17


## Основные параметры домена
realm: astrakhan-dobycha.gazprom.ru
domain_admin: 'Администратор'
administrator_domain_password: 'P@ssw0rd'

trust_realm: win.nornik.ru

## Адреса внешних NTP адресов
chrony_servers:
  - 192.168.100.1
