---
ansible_user: admin
ansible_ssh_pass: 'P@ssw0rd'
ansible_become_pass: 'P@ssw0rd'

## Изменения адреса в репозитории для всех серверов
repo_url: "https://repo1.red-soft.ru/redos/7.3/"

## Адрес внешнего DNS
dns_external:
  - 192.168.100.1

## Адрес внутреннего DNS (адреса контроллеров)
dns_internal:
  - 192.168.100.50

## Основные параметры домена
realm: esk.lab
domain_admin: 'Administrator'
administrator_domain_password: 'P@ssw0rd'

## Параметры траста
trust_realm:
  - name: gazprom.ru
    dns:
      - 192.168.100.12

## Адреса внешних NTP адресов
chrony_servers:
  - 192.168.100.1
