---
## Для роли base_setup, если необходимо создать пользователя
create_user: true
rename_server: true

## Список пакетов, которые необходимо установить на DC
base_packets:
  - samba*
  - krb5*
  - bind

## Список служб, которые необходимо установить на DC и запустить
services:
  - pkg_name: firewalld
    service_name: firewalld
  - pkg_name: qemu-guest-agent
    service_name: qemu-guest-agent

## Список необходимых портов
ports:
  - 53/tcp
  - 53/udp
  - 88/tcp
  - 88/udp
  - 123/udp
  - 135/tcp
  - 137/udp
  - 138/udp
  - 139/tcp
  - 389/tcp
  - 389/udp
  - 445/tcp
  - 464/tcp
  - 464/udp
  - 636/tcp
  - 3268/tcp
  - 3269/tcp
  - 49152-65535/tcp
