---
## Для роли base_setup, если необходимо создать пользователя
base_setup_create_user: true
base_setup_rename_server: true

## Список пакетов, которые необходимо установить на файловый сервер
base_packets:
  - bash-completion
  - samba-winbind
  - samba-winbind-clients
  - samba
  - pam_krb5
  - krb5-workstation
  - chrony
  - samba-winbind-krb5-locator
  - quota
  - adcli
  - python2-libselinux
  - join-to-domain
  - adcli


## Список служб, которые необходимо установить на файловый сервер
services:
  - pkg_name: firewalld
    service_name: firewalld
  - pkg_name: qemu-guest-agent
    service_name: qemu-guest-agent
ports:
  - 161/udp
  - 445/tcp

## Каталог для общего доступа. Также описание разрашений для ACL
share:
  dir: /exports/pub
  permissions: '2777'
  owner: root
  main_group: "{{ realm.split('.', 1)[0] | upper }}\\Domain Admins"
  # setfacl_group:
  #   - name: "{{ realm.split('.', 1)[0] | upper }}\\Domain Admins"
  #     permissions: rwx
    # - name: "{{ realm.split('.', 1)[0] | upper }}\\ServerAdmins"
    #   permissions: rwx

## Параметры каталога общего достпа (группы, кому доступен каталог и административные группы)
valid_users:
  - "@{{ realm.split('.', 1)[0] | upper }}\\Domain Users"
# admin_users:
#   - "@{{ realm.split('.', 1)[0] | upper }}\\Domain Admins"
#   - "@{{ trust_realm.split('.', 1)[0] | upper }}\\Domain Admins"
