---
## Для роли base_setup, если необходимо создать пользователя
base_setup_create_user: true
base_setup_rename_server: true

## Список пакетов, которые необходимо установить на файловый сервер
base_packets:
  - bash-completion
  - samba*.x86_64
  - join-to-domain
  - realmd
  - oddjob-mkhomedir
  - oddjob
  - samba-winbind-clients
  - samba-winbind
  - samba-common-tools
  - sssd-winbind-idmap
  - krb5-workstation*.x86_64
  - adcli

## Список служб, которые необходимо установить на файловый сервер
services:
  - pkg_name: firewalld
    service_name: firewalld
  - pkg_name: qemu-guest-agent
    service_name: qemu-guest-agent
ports:
  - 161/udp
  - 445/tcp

## Каталог для общего доступа
share_dir: /exports/pub
